Jinaga.Test/Model/Order.cs, Jinaga.Test/SpecificationTest.cs, Jinaga/Generators/CodeExpressionVisitor.cs, Jinaga/Generators/RecommendationEngine.cs
- Recommend joins to multiple predecessors
- Recommend a multiple join when roles are reversed
- Test with extension style
=> collection error

Jinaga.NET.sln, Jinaga/Facts/Fact.cs, Jinaga/Managers/NetworkManager.cs
Fails to pull all facts from the replicator. It only pulled the first page,
and then moved on to the next feed. Keep looping over same feed until we
reach the end.
Also:
- Serialize boolean field values.
- Remove Android and iOS projects
=> Fix bookmark loop

Jinaga.Test/SpecificationTest.cs, Jinaga/Projections/Specification.cs
Generates the full query suitable for the /read endpoint
=> Pass given facts into ToDescriptiveString

Jinaga/Jinaga.cs, Jinaga/Projections/Specification.cs, Jinaga/Repository/FactRepository.cs, Jinaga/Specification.cs
Validates that the givens are correct.
=> Move the ToDescriptiveString method to the generic type.

.github/workflows/build-test.yml, Documentation/Blog.dib, Jinaga.Graphviz/Jinaga.Graphviz.csproj, Jinaga.Graphviz/Renderer.cs, Jinaga.Test/Jinaga.Test.csproj, Jinaga.UnitTest/Jinaga.UnitTest.csproj, Jinaga/Jinaga.csproj
Also correct string escape issues in Jinaga.Graphviz
=> Upgrade to .NET 6

Jinaga.Test/Specifications/SpecificationTest.cs, Jinaga/Repository/FactRepository.cs, Jinaga/Repository/SpecificationProcessor.cs
Support more LINQ constructs:
- source.Any(predicate)
- predicate && predicate
- facts.Any<T>(predicate)
=> Facts.Any<T>(predicate)

Jinaga.Store.SQLite/ConnectionFactory.cs, Jinaga/Http/HttpConnection.cs, Jinaga/Http/HttpNetwork.cs, Jinaga/JinagaClient.cs, Jinaga/Managers/FactManager.cs, Jinaga/Managers/LoadBatch.cs, Jinaga/Managers/NetworkManager.cs, Jinaga/Observers/IObservableCollection.cs, Jinaga/Observers/ObservableSource.cs, Jinaga/Observers/Observer.cs
- Post to the synchronization context
- Configure await
=> Post to the synchronization context

Jinaga.Test/Fakes/FakeNetwork.cs, Jinaga.Test/Observers/WatchFromNetworkTest.cs, Jinaga/Managers/LoadBatch.cs, Jinaga/Managers/NetworkManager.cs, Jinaga/Storage/MemoryStore.cs
- Test loading office name from another feed
- Log calls to Load
- Protect the batch from concurrency
=> Network concurrency

Jinaga.Store.SQLite.Test/StoreTest.cs, Jinaga.Store.SQLite/ConnectionFactory.cs, Jinaga.Store.SQLite/SQLiteStore.cs
Added bookmark and mru load and save.  All tests passed.
=> Bookmark mru

Jinaga.Store.SQLite/JinagaSQLiteClient.cs, Jinaga.Test/Fakes/FakeNetwork.cs, Jinaga.Test/JinagaClientTest.cs, Jinaga.UnitTest/JinagaTest.cs, Jinaga.UnitTest/SimulatedNetwork.cs, Jinaga/DefaultImplementations/LocalNetwork.cs, Jinaga/Http/HttpConnection.cs, Jinaga/Http/HttpNetwork.cs, Jinaga/Http/IHttpAuthenticationProvider.cs, Jinaga/Http/WebClient.cs, Jinaga/JinagaClient.cs, Jinaga/Managers/FactManager.cs, Jinaga/Managers/NetworkManager.cs, Jinaga/Services/INetwork.cs, Jinaga/UserProfile.cs
The authentication provider adds headers or cookies to each request sent to the replicator.
=> Configure an authentication provider

.github/workflows/build-test.yml, .github/workflows/nuget.yml, Jinaga.Store.SQLite/Builder/ResultDescriptionBuilder.cs, Jinaga.Store.SQLite/ConnectionFactory.cs, Jinaga.Store.SQLite/Description/QueryDescription.cs, Jinaga.Store.SQLite/Jinaga.Store.SQLite.csproj, Jinaga.Store.SQLite/JinagaSQLiteClient.cs, Jinaga.Store.SQLite/SQLiteStore.cs, Jinaga/JinagaClient.cs, Jinaga/Managers/NetworkManager.cs, Jinaga/Services/IStore.cs, Jinaga/Storage/MemoryStore.cs
- Inherit client options
- List known referenes
- Use MinVer for SQLite package
- Return unsatisfiable specification if type is not known
- Notify application of status changes
- Queue facts in memory and SQL store
- Build and deploy the SQLite package
=> Prepare SQLite package

Jinaga.Store.SQLite/Builder/ResultDescriptionBuilder.cs, Jinaga.Store.SQLite/Generation/SqlGenerator.cs, Jinaga.Store.SQLite/SQLiteStore.cs, Jinaga/Observers/Observer.cs
- Fix bug causing duplicate notification
- Return no products for unsatisfiable queries
=> Fixed bugs related to first fetch

Jinaga.Store.SQLite.Test/QueryTest.cs, Jinaga.Test/Specifications/ProjectionVersioningTest.cs, Jinaga/JinagaClient.cs, Jinaga/Managers/Deserializer.cs, Jinaga/Managers/Projector.cs, Jinaga/Projections/HashProjection.cs, Jinaga/Repository/SpecificationProcessor.cs, Jinaga/Storage/MemoryStore.cs
- Expose the fact hash
- Test version consistency
=> Return fact hash

Jinaga.Store.SQLite.Test/StoreTest.cs, Jinaga.Store.SQLite/ConnectionFactory.cs, Jinaga.Store.SQLite/SQLite.cs, Jinaga.Store.SQLite/SQLiteStore.cs
- Improve error message from SQLite
- Use parameters for all SQLite queries
=> Remove string interpolation of values from SQLite code

Jinaga.Test/Facts/SerializeTest.cs, Jinaga.Test/Facts/VersioningTest.cs, Jinaga.Test/Model/School.cs, Jinaga/Facts/FieldValue.cs, Jinaga/Serialization/DeserializerCache.cs, Jinaga/Serialization/Interrogate.cs, Jinaga/Serialization/SerializerCache.cs
- Validate the properties of a fact
- Serialize and deserialize Guid and Guid?
- Test versioning with Guids
=> Accept Guid fields

Jinaga.Test/WatchTest.cs, Jinaga/JinagaClient.cs
=> Add Watch and Subscribe methods for givens with two specifications

Jinaga.Store.SQLite.Test/Observers/WatchFromNetworkTest.cs, Jinaga.Store.SQLite.Test/QueryTest.cs, Jinaga.Store.SQLite.Test/StoreTest.cs, Jinaga.Store.SQLite/JinagaSQLiteClient.cs, Jinaga.Store.SQLite/ResultSetTree.cs, Jinaga.Store.SQLite/SQLiteStore.cs, Jinaga.Test/Observers/SubscribeFromNetworkTest.cs, Jinaga.Test/Observers/WatchFromNetworkTest.cs, Jinaga.Test/QueryLocalTest.cs, Jinaga.UnitTest/JinagaTest.cs, Jinaga/Http/HttpConnection.cs, Jinaga/Http/HttpNetwork.cs, Jinaga/Http/ObservableStream.cs, Jinaga/Jinaga.csproj, Jinaga/JinagaClient.cs, Jinaga/Managers/FactManager.cs, Jinaga/Managers/NetworkManager.cs, Jinaga/Managers/Subscriber.cs, Jinaga/Observers/Observer.cs
=> Log to the provided logger factory

Jinaga.Test/Pipelines/InverseTest.cs, Jinaga.Test/Specifications/DistributionRuleTest.cs, Jinaga.Test/Specifications/SpecificationTest.cs, Jinaga/Repository/SpecificationProcessor.cs, Jinaga/Specification.cs
- **Added Select method to specify identity**
- **Test projections from identity**
- **Test inverses based on identity**
=> identity specification

Jinaga.Notebooks/Dot/Renderer.cs
=> Filter out duplicate types

Jinaga.Test/Specifications/SpecificationTest.cs, Jinaga/Repository/SpecificationProcessor.cs, Jinaga/Specifications/SourceContext.cs
Add support for short name in join expressions and improve label handling in source processing
=> Generate good labels in specifications

Jinaga.Notebooks/DataFrameExtensions.cs
Add support for Guid properties in DataFrameExtensions and handle unsupported types with string conversion
=> Make AsTable more robust
